require('dotenv').config()
const mongoose = require('mongoose')
const express = require('express')
const cors = require('cors')
mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('MongoDB connected'))
  .catch((err) => console.log('MongoDB error:', err))
const app = express()
app.use(cors())
app.use(express.json())
app.get('/',(req,res) => {
    res.json({message: 'CalmHands Backend Running'})
})
app.listen(5000, () => {
    console.log('Server running on port 5000')
})